---
## Config Server

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_url: "http://config-server-svc"

---
# Mysql

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  hostname: "mysql-0.mysql"

---
# PVC

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard # GCP 에서 제공하는 PV 사용
  accessModes:
    - ReadWriteOnce

---
# StatefulSet - Mariadb


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql # 헤드리스 서비스 이름
  replicas: 1
  template:
    metadata:
      labels:
        # 서비스가 해당 label 을 찾는다.
        app: mysql
    spec:
      containers:
      - name: mysql
        # 가장 최신 버전 mysql 을 사용한다.
        image: mysql:latest
        ports:
        - containerPort: 3306
          name: mysql
        env:
          # mysql 의 root passwrd 를 변경한다.
          # 각 서비스의 설정 파일에 지정한 값과 일치해야한다.
          - name: MYSQL_ROOT_PASSWORD
            value: root
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
            # 데이터베이스가 지정한 경로에 생성된다.
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-cm

---
# ConfigMap

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-cm
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS order_db;
    CREATE DATABASE IF NOT EXISTS payment_db;
    CREATE DATABASE IF NOT EXISTS product_db;

---
# 스테이트풀셋 멤버의 안정적인 DNS 엔트리를 위한 헤드리스 서비스
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-app
        image: redis:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 6379
        command:
          - "redis-server"
        args:
          - "--protected-mode"
          - "no"

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-app
  ports:
  - port: 6379
    targetPort: 6379

---
## Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"

---
## Service

apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
spec:
  selector:
    app: zipkin
  ports:
  - port: 9411
    targetPort: 9411

---
## Service-LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: zipkin-lb-svc
spec:
  type: LoadBalancer
  selector:
    app: zipkin
  ports:
  - port: 9411
    targetPort: 9411
