apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  labels:
    app: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-app
        image: redis:7.2.1
        command:
          - "redis-server"
        ports:
        - containerPort: 6379
        
        args:
          - "--protected-mode"
          - "no"

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  # 로드밸런서 IP 설정이 왜 없지? (GCP 내부 IP 설정?)
  selector:
    app: redis-app
  ports:
  - port: 6379
    targetPort: 6379

---
